### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by davidpersson** [UnionOfRAD/lithium#1224]
This is a meta bug, tracking and organizing the effort in making 1.1 PHP 7 compatible.

- [x] no PHP internal deprecation warnings
- [x] fix string class loading
- [x] Fix segfault in tests #1236
- [x] Fix #1240 
- [x] all tests green

**Comment by shopblocks** [comment]
While running the tests locally, I have an issue which says: 

```
Failed assertion assertEqual.
 File    : /var/www/vhosts/lithium/tests/cases/net/http/MediaTest.php
 Class   : lithium\tests\cases\net\http\MediaTest
 Method  : testMediaTypes()
 Line    : 39
 ________
trace: [0]
expected: array (
  0 => 'html',
  1 => 'htm',
  2 => 'form',
  3 => 'json',
  4 => 'rss',
  5 => 'atom',
  6 => 'css',
  7 => 'js',
  8 => 'text',
  9 => 'txt',
  10 => 'xml',
)
result: array (
  0 => 'view-integration-test',
  1 => 'html',
  2 => 'htm',
  3 => 'form',
  4 => 'json',
  5 => 'rss',
  6 => 'atom',
  7 => 'css',
  8 => 'js',
  9 => 'text',
  10 => 'txt',
  11 => 'xml',
)
```

Do you have any idea why this would be failing? 

Is there a specific setup I need to test this properly.

I currently just have the repository cloned and run `bash console/li3 test tests`

**Comment by davidpersson** [comment]
This seems to be another issue unrelated to compatibility. Your best bet is to open a new ticket for this.

**Comment by shopblocks** [comment]
issue opened https://github.com/UnionOfRAD/lithium/issues/1225

**Comment by shopblocks** [comment]
I have found the cause of the issue for the `PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /var/www/vhosts/lithium/util/String.php on line 27` issue when running tests.

It is caused by the AffectedTest.php test running,

it runs `Affected::apply()`, which then runs `self::_affected($test->subject())`

This then runs a `Libraries::find(true, compact('exclude') + array('recursive' => true));`

```php
Array
(
    [0] => lithium\util\Collection
    [1] => lithium\util\Inflector
    [2] => lithium\util\Set
    [3] => lithium\util\String
    [4] => lithium\util\Text
    [5] => lithium\util\Validator
    [6] => lithium\util\collection\Filters
    [7] => lithium\test\Controller
    [8] => lithium\test\Dispatcher
    [9] => lithium\test\Filter
    [10] => lithium\test\Group
    [11] => lithium\test\Integration
    [12] => lithium\test\Mocker
    [13] => lithium\test\MockerChain
    [14] => lithium\test\Report
    [15] => lithium\test\Unit
    [16] => lithium\test\filter\Affected
    [17] => lithium\test\filter\Complexity
    [18] => lithium\test\filter\Coverage
    [19] => lithium\test\filter\Profiler
    [20] => lithium\template\Helper
    [21] => lithium\template\TemplateException
    [22] => lithium\template\View
    [23] => lithium\template\view\Compiler
    [24] => lithium\template\view\Renderer
    [25] => lithium\template\view\adapter\File
    [26] => lithium\template\view\adapter\Simple
    [27] => lithium\template\helper\Form
    [28] => lithium\template\helper\Html
    [29] => lithium\template\helper\Security
    [30] => lithium\storage\Cache
    [31] => lithium\storage\Session
    [32] => lithium\storage\session\strategy\Encrypt
    [33] => lithium\storage\session\strategy\Hmac
    [34] => lithium\storage\session\strategy\MissingSignatureException
    [35] => lithium\storage\session\adapter\Cookie
    [36] => lithium\storage\session\adapter\Memory
    [37] => lithium\storage\session\adapter\Php
    [38] => lithium\storage\cache\Adapter
    [39] => lithium\storage\cache\strategy\Base64
    [40] => lithium\storage\cache\strategy\Json
    [41] => lithium\storage\cache\strategy\Serializer
    [42] => lithium\storage\cache\adapter\Apc
    [43] => lithium\storage\cache\adapter\File
    [44] => lithium\storage\cache\adapter\Memcache
    [45] => lithium\storage\cache\adapter\Memory
    [46] => lithium\storage\cache\adapter\Redis
    [47] => lithium\storage\cache\adapter\XCache
    [48] => lithium\security\Auth
    [49] => lithium\security\Hash
    [50] => lithium\security\Password
    [51] => lithium\security\Random
    [52] => lithium\security\validation\FormSignature
    [53] => lithium\security\validation\RequestToken
    [54] => lithium\security\auth\adapter\Form
    [55] => lithium\security\auth\adapter\Http
    [56] => lithium\net\Message
    [57] => lithium\net\Socket
    [58] => lithium\net\socket\Context
    [59] => lithium\net\socket\Curl
    [60] => lithium\net\socket\Stream
    [61] => lithium\net\http\Auth
    [62] => lithium\net\http\ClientMediaException
    [63] => lithium\net\http\Media
    [64] => lithium\net\http\MediaException
    [65] => lithium\net\http\Message
    [66] => lithium\net\http\Request
    [67] => lithium\net\http\Response
    [68] => lithium\net\http\Route
    [69] => lithium\net\http\Router
    [70] => lithium\net\http\RoutingException
    [71] => lithium\net\http\Service
    [72] => lithium\g11n\Catalog
    [73] => lithium\g11n\Locale
    [74] => lithium\g11n\Message
    [75] => lithium\g11n\Multibyte
    [76] => lithium\g11n\multibyte\adapter\Iconv
    [77] => lithium\g11n\multibyte\adapter\Intl
    [78] => lithium\g11n\multibyte\adapter\Mbstring
    [79] => lithium\g11n\catalog\Adapter
    [80] => lithium\g11n\catalog\adapter\Code
    [81] => lithium\g11n\catalog\adapter\Gettext
    [82] => lithium\g11n\catalog\adapter\Memory
    [83] => lithium\g11n\catalog\adapter\Php
    [84] => lithium\data\Collection
    [85] => lithium\data\Connections
    [86] => lithium\data\DocumentSchema
    [87] => lithium\data\Entity
    [88] => lithium\data\Model
    [89] => lithium\data\Schema
    [90] => lithium\data\Source
    [91] => lithium\data\source\Database
    [92] => lithium\data\source\Http
    [93] => lithium\data\source\Mock
    [94] => lithium\data\source\MongoDb
    [95] => lithium\data\source\Result
    [96] => lithium\data\source\mongo_db\Exporter
    [97] => lithium\data\source\mongo_db\Result
    [98] => lithium\data\source\mongo_db\Schema
    [99] => lithium\data\source\http\adapter\CouchDb
    [100] => lithium\data\source\database\adapter\MySql
    [101] => lithium\data\source\database\adapter\PostgreSql
    [102] => lithium\data\source\database\adapter\Sqlite3
    [103] => lithium\data\source\database\adapter\pdo\Result
    [104] => lithium\data\model\Query
    [105] => lithium\data\model\QueryException
    [106] => lithium\data\model\Relationship
    [107] => lithium\data\entity\Document
    [108] => lithium\data\entity\Record
    [109] => lithium\data\collection\DocumentSet
    [110] => lithium\data\collection\MultiKeyRecordSet
    [111] => lithium\data\collection\RecordSet
    [112] => lithium\core\Adaptable
    [113] => lithium\core\ClassNotFoundException
    [114] => lithium\core\ConfigException
    [115] => lithium\core\Configuration
    [116] => lithium\core\Environment
    [117] => lithium\core\ErrorHandler
    [118] => lithium\core\Libraries
    [119] => lithium\core\NetworkException
    [120] => lithium\core\Object
    [121] => lithium\core\StaticObject
    [122] => lithium\console\Command
    [123] => lithium\console\Dispatcher
    [124] => lithium\console\Request
    [125] => lithium\console\Response
    [126] => lithium\console\Router
    [127] => lithium\console\command\Create
    [128] => lithium\console\command\G11n
    [129] => lithium\console\command\Help
    [130] => lithium\console\command\Route
    [131] => lithium\console\command\Test
    [132] => lithium\console\command\g11n\Extract
    [133] => lithium\console\command\create\Controller
    [134] => lithium\console\command\create\Mock
    [135] => lithium\console\command\create\Model
    [136] => lithium\console\command\create\Test
    [137] => lithium\console\command\create\View
    [138] => lithium\analysis\Debugger
    [139] => lithium\analysis\Docblock
    [140] => lithium\analysis\Inspector
    [141] => lithium\analysis\Logger
    [142] => lithium\analysis\Parser
    [143] => lithium\analysis\logger\adapter\Cache
    [144] => lithium\analysis\logger\adapter\File
    [145] => lithium\analysis\logger\adapter\FirePhp
    [146] => lithium\analysis\logger\adapter\Growl
    [147] => lithium\analysis\logger\adapter\Syslog
    [148] => lithium\action\Controller
    [149] => lithium\action\DispatchException
    [150] => lithium\action\Dispatcher
    [151] => lithium\action\Request
    [152] => lithium\action\Response
)
```

Which, as you can see [3] is the offender.

This then goes through the `Inspector::dependencies()` which runs the class, which throws the error.

@davidpersson I don't see any way to keep the file in there, if you want to do the Libraries::find() as it currently does get done.

**Comment by davidpersson** [comment]
@shopblocks Thanks a lot for investigating the cause. I'll have a look at this as soon as I get some time.

**Comment by shopblocks** [comment]
No problem. I'll keep trying to find a solution, but so far i'm coming up blank.

**Comment by shopblocks** [comment]
I have tried everything I can think of, and the only thing that has worked so far, has been removing the String class.

**Comment by shopblocks** [comment]
https://github.com/UnionOfRAD/lithium/pull/1234

Seems like it may be the only way to go other than deleting the files.

It will still throw deprecation errors on < PHP 7, but PHP7+ will not use the file at all.

**Comment by davidpersson** [comment]
Let me look into this issue. For the time being: Does PHP7 elsewise run cleanly - without any warnings, notices, deprecation warnings?

**Comment by shopblocks** [comment]
Well. It gets further into the tests, I still have the mediaTest issues, so cannot say it passes them all, but it gets further.

**Comment by davidpersson** [comment]
The media test issues should've been solved by d25f48cc0f5bdd813f10d9ed35ab47d0198cb1fb, I forgot to merge that change into 1.1 -- which I just did now.

**Comment by shopblocks** [comment]
Seems alright.

Some new failures now though in the 1.1 branch.

```
6648 / 6649 passes
1 fail and 0 exceptions

Failed assertion assertPattern.
 File    : /var/www/vhosts/lithium/tests/cases/console/command/HelpTest.php
 Class   : lithium\tests\cases\console\command\HelpTest
 Method  : testRunWithName()
 Line    : 60
 ________
expected: '/li3 test \\[\\-\\-filters\\=\\<string\\>\\] \\[\\-\\-format\\=\\<string\\>\\] \\[\\-\\-verbose\\] \\[\\-\\-silent\\] \\[\\-\\-plain\\] \\[\\-\\-help\\] \\[\\<path\\>\\]/'
result: 'USAGE
    li3 test [--filters=<string>] [--format=<string>] [--verbose] [--just-assertions] [--silent] [--plain] [--help] [<path>]
DESCRIPTION
Runs a given set of tests and outputs the results.
OPTIONS
    <path>
        Absolute or relative path to tests or a file which
                            corresponding test should be run.
    --filters=<string>
        List of filters to apply before/during/after test run, separated by commas.
    --format=<string>
        Format to use for rendering results. Any other format than `txt` will
        cause the command to enter quiet mode, surpressing headers and any other
        decoration.
    --verbose
        Enable verbose output especially for the `txt` format.
    --just-assertions
        Prevent any headers or similar decoration being output.
        Good for command calls embedded into other scripts.
    --silent
        Surpresses all output except errors.
    --plain
        Enables plain output by i.e. disabling colors. Useful when piping into other commands.
    --help
        Shows help for the command. Alternatively `-h` can be used.
USAGE
    li3 test [--filters=<string>] [--format=<string>] [--verbose] [--just-assertions] [--silent] [--plain] [--help] [<path>]
DESCRIPTION
Runs a given set of tests and outputs the results.
OPTIONS
    <path>
        Absolute or relative path to tests or a file which
                            corresponding test should be run.
    --filters=<string>
        List of filters to apply before/during/after test run, separated by commas.
    --format=<string>
        Format to use for rendering results. Any other format than `txt` will
        cause the command to enter quiet mode, surpressing headers and any other
        decoration.
    --verbose
        Enable verbose output especially for the `txt` format.
    --just-assertions
        Prevent any headers or similar decoration being output.
        Good for command calls embedded into other scripts.
    --silent
        Surpresses all output except errors.
    --plain
        Enables plain output by i.e. disabling colors. Useful when piping into other commands.
    --help
        Shows help for the command. Alternatively `-h` can be used.
'

 ________
```

**Comment by shopblocks** [comment]
I have a fix for the above, if you want me to submit a PR. it is just changing HelpTest.php:57 to be:

```php
		$expected .= ' [--format=<string>] [--verbose] [--just-assertions] [--silent] [--plain] [--help] [<path>]';
```

**Comment by shopblocks** [comment]
https://github.com/UnionOfRAD/lithium/pull/1235 submitted

**Comment by shopblocks** [comment]
We're getting close now. Last few errors.

1) Still getting the errors in the MemcacheTest. If i implement sleep(5) these two go:

```
Failed assertion assertFalse.
 File    : /var/www/vhosts/lithium/tests/integration/storage/cache/adapter/MemcacheTest.php
 Class   : lithium\tests\integration\storage\cache\adapter\MemcacheTest
 Method  : testWriteExpiryExpires()
 Line    : 157
 ________
expected: false
result: 'data0'

 ________

Failed assertion assertFalse.
 File    : /var/www/vhosts/lithium/tests/integration/storage/cache/adapter/MemcacheTest.php
 Class   : lithium\tests\integration\storage\cache\adapter\MemcacheTest
 Method  : testWriteExpiryExpires()
 Line    : 160
 ________
expected: false
result: 'data1'

 ________
```

2) Some var_export error. This only happens on PHP 7, 5.6 is fine. Not found the cause of this yet.

```
ErrorException (E_WARNING) thrown.
 File    : /var/www/vhosts/lithium/test/Unit.php
 Class   : lithium\test\Unit
 Method  : lithium\test\{closure}()
 Line    : 1872
 ________
var_export does not handle circular references
 ________
var_export, line ??
lithium\test\Unit::_message(), line 1872
lithium\test\Unit::assert(), line 237
lithium\test\Unit::assertArrayHasKey(), line 957
lithium\tests\cases\test\MockerTest::testMagicCallGetStoredResultsWhenCalled(), line 416
lithium\test\Unit::lithium\test\{closure}() @ ?, line 1611
lithium\core\Object::_filter(), line 263
lithium\test\Unit::_runTestMethod(), line 1615
lithium\test\Unit::run(), line 213
lithium\util\Collection::invoke(), line 193
lithium\util\Collection::__call(), line 207
lithium\test\Report::run(), line 147
lithium\test\Dispatcher::run()::{closure} @ 65, line 69
lithium\core\StaticObject::_filter(), line 140
lithium\test\Dispatcher::run(), line 73
lithium\console\command\Test::run()::{closure} @ 235, line 236
lithium\console\command\Test::lithium\console\command\{closure}() @ ?, line 145
lithium\console\command\Test::run(), line 238
lithium\core\Object::invokeMethod(), line 179
lithium\console\Command::__invoke(), line 139
lithium\console\Dispatcher::lithium\console\{closure}() @ ?, line 198
lithium\core\StaticObject::_filter(), line 140
lithium\console\Dispatcher::_call(), line 201
lithium\core\StaticObject::invokeMethod(), line 84
lithium\console\Dispatcher::run()::{closure} @ 95, line 105
lithium\core\StaticObject::_filter(), line 140
lithium\console\Dispatcher::run(), line 109
/var/www/vhosts/lithium/console/lithium.php::{closure} @ 74, line 75
[main], line 110
 ________

ErrorException (E_WARNING) thrown.
 File    : /var/www/vhosts/lithium/test/Unit.php
 Class   : lithium\test\Unit
 Method  : lithium\test\{closure}()
 Line    : 1872
 ________
var_export does not handle circular references
 ________
var_export, line ??
lithium\test\Unit::_message(), line 1872
lithium\test\Unit::assert(), line 237
lithium\test\Unit::assertArrayHasKey(), line 957
lithium\tests\cases\test\MockerTest::testMagicCallGetStoredResultsWhenCalledIndirectly(), line 436
lithium\test\Unit::lithium\test\{closure}() @ ?, line 1611
lithium\core\Object::_filter(), line 263
lithium\test\Unit::_runTestMethod(), line 1615
lithium\test\Unit::run(), line 213
lithium\util\Collection::invoke(), line 193
lithium\util\Collection::__call(), line 207
lithium\test\Report::run(), line 147
lithium\test\Dispatcher::run()::{closure} @ 65, line 69
lithium\core\StaticObject::_filter(), line 140
lithium\test\Dispatcher::run(), line 73
lithium\console\command\Test::run()::{closure} @ 235, line 236
lithium\console\command\Test::lithium\console\command\{closure}() @ ?, line 145
lithium\console\command\Test::run(), line 238
lithium\core\Object::invokeMethod(), line 179
lithium\console\Command::__invoke(), line 139
lithium\console\Dispatcher::lithium\console\{closure}() @ ?, line 198
lithium\core\StaticObject::_filter(), line 140
lithium\console\Dispatcher::_call(), line 201
lithium\core\StaticObject::invokeMethod(), line 84
lithium\console\Dispatcher::run()::{closure} @ 95, line 105
lithium\core\StaticObject::_filter(), line 140
lithium\console\Dispatcher::run(), line 109
/var/www/vhosts/lithium/console/lithium.php::{closure} @ 74, line 75
[main], line 110
 ________
```

3) New error to do with ContextTest.php. Not tracked this down yet.

```
ErrorException (E_WARNING) thrown.
 File    : /var/www/vhosts/lithium/tests/cases/net/socket/ContextTest.php
 Class   : lithium\test\Unit
 Method  : lithium\test\{closure}()
 Line    : 33
 ________
rewind(): stream does not support seeking
 ________
rewind, line ??
lithium\tests\cases\net\socket\ContextTest::setUp()::{closure} @ 61, line 33
lithium\test\Mocker::callFunction(), line 810
lithium\tests\cases\net\socket\stream_context_get_options, line 10
lithium\tests\cases\net\socket\ContextTest::testGetSetTimeout(), line 95
lithium\test\Unit::lithium\test\{closure}() @ ?, line 1611
lithium\core\Object::_filter(), line 263
lithium\test\Unit::_runTestMethod(), line 1615
lithium\test\Unit::run(), line 213
lithium\util\Collection::invoke(), line 193
lithium\util\Collection::__call(), line 207
lithium\test\Report::run(), line 147
lithium\test\Dispatcher::run()::{closure} @ 65, line 69
lithium\core\StaticObject::_filter(), line 140
lithium\test\Dispatcher::run(), line 73
lithium\console\command\Test::run()::{closure} @ 235, line 236
lithium\console\command\Test::lithium\console\command\{closure}() @ ?, line 145
lithium\console\command\Test::run(), line 238
lithium\core\Object::invokeMethod(), line 179
lithium\console\Command::__invoke(), line 139
lithium\console\Dispatcher::lithium\console\{closure}() @ ?, line 198
lithium\core\StaticObject::_filter(), line 140
lithium\console\Dispatcher::_call(), line 201
lithium\core\StaticObject::invokeMethod(), line 84
lithium\console\Dispatcher::run()::{closure} @ 95, line 105
lithium\core\StaticObject::_filter(), line 140
lithium\console\Dispatcher::run(), line 109
/var/www/vhosts/lithium/console/lithium.php::{closure} @ 74, line 75
[main], line 110
 ________
```

4) Another ContextTest failure.

```
Failed assertion assertPattern.
 File    : /var/www/vhosts/lithium/tests/cases/net/socket/ContextTest.php
 Class   : lithium\tests\cases\net\socket\ContextTest
 Method  : testContextAdapter()
 Line    : 178
 ________
expected: '/<title[^>]*>301 Moved<\\/title>/im'
result: '<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-GB"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/logos/doodles/2015/beethovens-245th-birthday-4687587541254144-hp.jpg" itemprop="image"><meta content="Help Beethoven arrange his masterpieces in today&#8217;s #GoogleDoodle" property="og:description"><meta content="http://www.google.com/logos/doodles/2015/celebrating-ludwig-van-beethovens-245th-year-4687587541254144.3-thp.png" property="og:image"><meta content="536" property="og:image:width">

...

```

__Not sure if any of the following have any basis on this__

```
Skip `The `xdebug` extension is not loaded.`.
 Class   : lithium\tests\integration\test\FilterTest
 Method  : skip()

Skip `No PHP session support in cli SAPI.`.
 Class   : lithium\tests\integration\storage\SessionTest
 Method  : testPhpReadWriteDelete()

Skip `No headers support in cli SAPI.`.
 Class   : lithium\tests\integration\storage\SessionTest
 Method  : testCookieReadWriteDelete()

Skip `No PHP session support in cli SAPI.`.
 Class   : lithium\tests\integration\storage\SessionTest
 Method  : testNamespacesWithPhpAdapter()

Skip `No PHP session support in cli SAPI.`.
 Class   : lithium\tests\integration\storage\SessionTest
 Method  : testHmacStrategyWithPhpAdapter()

Skip `No PHP session support in cli SAPI.`.
 Class   : lithium\tests\integration\storage\SessionTest
 Method  : testEncryptStrategyWithPhpAdapter()

Skip `The redis extension is not installed.`.
 Class   : lithium\tests\integration\storage\cache\adapter\RedisTest
 Method  : skip()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip ``MySqlSchemaTest` Not supported by the `''` adapter`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip ``PostgreSqlSchemaTest` Not supported by the `''` adapter`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip ``Sqlite3SchemaTest` Not supported by the `''` adapter`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `The `test` connection is not correctly configured.`.
 Class   : lithium\tests\integration\data\Base
 Method  : skipIf()

Skip `No default app template.`.
 Class   : lithium\tests\cases\template\view\adapter\FileTest
 Method  : testTemplateLocating()

Skip `Cookie tests cannot be run via command-line interface.`.
 Class   : lithium\tests\cases\storage\session\adapter\CookieTest
 Method  : skip()

Skip `APC is either not loaded or not enabled.`.
 Class   : lithium\tests\cases\storage\cache\adapter\ApcTest
 Method  : skip()

Skip `The XCache extension is not installed or not configured for userspace caching.`.
 Class   : lithium\tests\cases\storage\cache\adapter\XCacheTest
 Method  : skip()

Skip `The `Intl` adapter is not enabled.`.
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IntlTest
 Method  : skip()

Skip `The `MongoDb` class is not enabled.`.
 Class   : lithium\tests\cases\data\source\MongoDbTest
 Method  : skip()

Skip `MongoDb is not enabled`.
 Class   : lithium\tests\cases\data\source\mongo_db\ExporterTest
 Method  : skip()

Skip `MongoDb is not enabled`.
 Class   : lithium\tests\cases\data\source\mongo_db\SchemaTest
 Method  : skip()

Skip `Refactoring original error-handling iteration.`.
 Class   : lithium\tests\cases\core\ErrorHandlerTest
 Method  : testErrorCatching()

Skip ``Phar support is read only.`.
 Class   : lithium\tests\cases\core\LibrariesTest
 Method  : testPathsInPharArchives()
```

**Comment by shopblocks** [comment]
Full output: https://gist.github.com/shopblocks/22b390245b6f2b7cb697

**Comment by alexbowers** [comment]
SegFault still exists in 7.0.1

**Comment by alexbowers** [comment]
SegFault has been fixed in 7.0.2 (Due Jan 2016)

For now, to get tests to pass, you need to go through the compilation process of php.

**Comment by davidpersson** [comment]
Please see #1251 for info on Object. We don't have to tackle this now as its not needed for PHP7 compat.

**Comment by alexbowers** [comment]
@davidpersson Second to the bottom can be marked off due to https://github.com/UnionOfRAD/lithium/issues/1240

**Comment by davidpersson** [comment]
Please note that the 1.1 is now compatible with PHP 7. The travis build using 7.0.1 fails the build using nightly (7.0.3-dev) is fine. We'll probably require >=7.0.3 for the 7 series.
